2024-03-26T23:03:34 {"cpu": 0.13623046875, "cpu_total": 16, "cpu_usage": 0.008514404296875, "memory": 2871.0, "memory_total": 9698.0, "memory_usage": 0.29604042070530007, "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 33 in schedule 4 is alive.", "timestamp": 1711494214.4496, "uuid": "a5ee86550cbc480f96ff9ea89dd02f41"}
2024-03-26T23:03:34 {"cpu": 0.13623046875, "cpu_total": 16, "cpu_usage": 0.008514404296875, "memory": 2907.0, "memory_total": 9698.0, "memory_usage": 0.2997525262940813, "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 33 in schedule 4 is alive.", "timestamp": 1711494214.649255, "uuid": "3200fd19ccb749a7b91125e731180d81"}
2024-03-26T23:03:34 {"block_run_id": 98, "block_uuid": "scrape_full_fore", "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Execute PipelineRun 33, BlockRun 98: pipeline fore_to_postgres block scrape_full_fore", "timestamp": 1711494214.686374, "uuid": "2a2e8b5075d848c3b965471d77a105d1"}
2024-03-26T23:03:44 {"cpu": 0.14453125, "cpu_total": 16, "cpu_usage": 0.009033203125, "memory": 2931.0, "memory_total": 9698.0, "memory_usage": 0.3022272633532687, "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 33 in schedule 4 is alive.", "timestamp": 1711494224.91537, "uuid": "8203bf29fc9343aba8480b364eb32012"}
2024-03-26T23:03:54 {"cpu": 0.1435546875, "cpu_total": 16, "cpu_usage": 0.00897216796875, "memory": 2934.0, "memory_total": 9698.0, "memory_usage": 0.30253660548566713, "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 33 in schedule 4 is alive.", "timestamp": 1711494234.183532, "uuid": "5db391819bc04b90be949154a3a6a302"}
2024-03-26T23:03:55 {"block_run_id": 98, "block_uuid": "scrape_full_fore", "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "BlockRun 98 (block_uuid: scrape_full_fore) completes.", "timestamp": 1711494235.743135, "uuid": "b5027123d79d452283672a6cd05416f1"}
2024-03-26T23:04:04 {"cpu": 0.1416015625, "cpu_total": 16, "cpu_usage": 0.00885009765625, "memory": 2883.0, "memory_total": 9698.0, "memory_usage": 0.2972777892348938, "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 33 in schedule 4 is alive.", "timestamp": 1711494244.45458, "uuid": "83d436c0bad54bb984f3250aba1139b5"}
2024-03-26T23:04:04 {"block_run_id": 99, "block_uuid": "trivial_transform", "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Execute PipelineRun 33, BlockRun 99: pipeline fore_to_postgres block trivial_transform", "timestamp": 1711494244.70153, "uuid": "baf3cc9bf98746fe9792df94f32b5a38"}
2024-03-26T23:04:05 {"block_run_id": 99, "block_uuid": "trivial_transform", "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "BlockRun 99 (block_uuid: trivial_transform) completes.", "timestamp": 1711494245.13241, "uuid": "7d8eb409aa884576b17135e5be59404f"}
2024-03-26T23:04:14 {"cpu": 0.1455078125, "cpu_total": 16, "cpu_usage": 0.00909423828125, "memory": 2877.0, "memory_total": 9698.0, "memory_usage": 0.29665910497009695, "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 33 in schedule 4 is alive.", "timestamp": 1711494254.804926, "uuid": "1cd7765955df4aa79f3764a7759cb13a"}
2024-03-26T23:04:15 {"block_run_id": 100, "block_uuid": "fore_to_postgres", "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Execute PipelineRun 33, BlockRun 100: pipeline fore_to_postgres block fore_to_postgres", "timestamp": 1711494255.047028, "uuid": "c97a81801a2c41c394b7339b83ddce31"}
2024-03-26T23:04:15 {"block_run_id": 100, "block_uuid": "fore_to_postgres", "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "BlockRun 100 (block_uuid: fore_to_postgres) completes.", "timestamp": 1711494255.399634, "uuid": "bc944b32aa6e4b078181e4b01cd6555a"}
2024-03-26T23:04:16 {"block_run_id": 101, "block_uuid": "test_split_postgres", "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Execute PipelineRun 33, BlockRun 101: pipeline fore_to_postgres block test_split_postgres", "timestamp": 1711494256.079054, "uuid": "7cc058bf9b504fb2935dfe47c9cc933e"}
2024-03-26T23:04:16 {"block_run_id": 101, "block_uuid": "test_split_postgres", "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "EXCEPTION", "message": "BlockRun 101 (block_uuid: test_split_postgres) failed.", "timestamp": 1711494256.39814, "uuid": "6118edf2b45e456299f9270cd506ee16", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 359, in export\n    __process()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 341, in __process\n    self.upload_dataframe(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py\", line 359, in upload_dataframe\n    cursor.copy_expert(f\"\"\"\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"test_scraped_forecasts_final_pkey\"\nDETAIL:  Key (mtn_name, elevation, local_time_issued, local_time_of_forecast)=(nanga_parbat, 8125, 2024-03-26 17:00:00, 2024-03-26 15:00:00) already exists.\nCONTEXT:  COPY test_scraped_forecasts_final, line 1\n\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1580, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["duplicate key value violates unique constraint \"test_scraped_forecasts_final_pkey\"\nDETAIL:  Key (mtn_name, elevation, local_time_issued, local_time_of_forecast)=(nanga_parbat, 8125, 2024-03-26 17:00:00, 2024-03-26 15:00:00) already exists.\nCONTEXT:  COPY test_scraped_forecasts_final, line 1\n"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_postgres
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 359, in export
    __process()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 341, in __process
    self.upload_dataframe(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py", line 359, in upload_dataframe
    cursor.copy_expert(f"""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "test_scraped_forecasts_final_pkey"
DETAIL:  Key (mtn_name, elevation, local_time_issued, local_time_of_forecast)=(nanga_parbat, 8125, 2024-03-26 17:00:00, 2024-03-26 15:00:00) already exists.
CONTEXT:  COPY test_scraped_forecasts_final, line 1

2024-03-26T23:04:24 {"cpu": 0.1494140625, "cpu_total": 16, "cpu_usage": 0.00933837890625, "memory": 2883.0, "memory_total": 9698.0, "memory_usage": 0.2972777892348938, "pipeline_run_id": 33, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 33 in schedule 4 is alive.", "timestamp": 1711494264.216531, "uuid": "9692f285376c43c5bf254f77ed25a56d"}
