2024-03-26T23:00:05 {"cpu": 0.1240234375, "cpu_total": 16, "cpu_usage": 0.00775146484375, "memory": 2855.0, "memory_total": 9698.0, "memory_usage": 0.2943905959991751, "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 32 in schedule 4 is alive.", "timestamp": 1711494005.216469, "uuid": "7bc417d743f84faa97b601a912de784f"}
2024-03-26T23:00:05 {"cpu": 0.1240234375, "cpu_total": 16, "cpu_usage": 0.00775146484375, "memory": 2889.0, "memory_total": 9698.0, "memory_usage": 0.2978964734996907, "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 32 in schedule 4 is alive.", "timestamp": 1711494005.466617, "uuid": "2bc14dce06c24d19bc666c113af5d25c"}
2024-03-26T23:00:05 {"block_run_id": 94, "block_uuid": "scrape_full_fore", "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Execute PipelineRun 32, BlockRun 94: pipeline fore_to_postgres block scrape_full_fore", "timestamp": 1711494005.552149, "uuid": "487817abb1ce4a2badcf44a481e764d5"}
2024-03-26T23:00:14 {"cpu": 0.1220703125, "cpu_total": 16, "cpu_usage": 0.00762939453125, "memory": 2918.0, "memory_total": 9698.0, "memory_usage": 0.3008867807795422, "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 32 in schedule 4 is alive.", "timestamp": 1711494014.736719, "uuid": "6d711197c276424e9cffe2d7b18efa13"}
2024-03-26T23:00:25 {"cpu": 0.1201171875, "cpu_total": 16, "cpu_usage": 0.00750732421875, "memory": 2919.0, "memory_total": 9698.0, "memory_usage": 0.300989894823675, "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 32 in schedule 4 is alive.", "timestamp": 1711494025.009627, "uuid": "73f4ed3836d9414483b4157b6f482955"}
2024-03-26T23:00:34 {"cpu": 0.119140625, "cpu_total": 16, "cpu_usage": 0.0074462890625, "memory": 2931.0, "memory_total": 9698.0, "memory_usage": 0.3022272633532687, "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 32 in schedule 4 is alive.", "timestamp": 1711494034.276074, "uuid": "d6b1cde7b7744456a040cf4c00fc8378"}
2024-03-26T23:00:36 {"block_run_id": 94, "block_uuid": "scrape_full_fore", "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "BlockRun 94 (block_uuid: scrape_full_fore) completes.", "timestamp": 1711494036.39664, "uuid": "e5a7a124b6b048a8a41048c4a8d10496"}
2024-03-26T23:00:44 {"cpu": 0.12744140625, "cpu_total": 16, "cpu_usage": 0.007965087890625, "memory": 2908.0, "memory_total": 9698.0, "memory_usage": 0.29985564033821405, "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 32 in schedule 4 is alive.", "timestamp": 1711494044.552634, "uuid": "6b22822469c54481ac62ae8ff419fa88"}
2024-03-26T23:00:44 {"block_run_id": 95, "block_uuid": "trivial_transform", "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Execute PipelineRun 32, BlockRun 95: pipeline fore_to_postgres block trivial_transform", "timestamp": 1711494044.774383, "uuid": "b6b9eedf192744ab859ca8942dd50fd7"}
2024-03-26T23:00:45 {"block_run_id": 95, "block_uuid": "trivial_transform", "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "BlockRun 95 (block_uuid: trivial_transform) completes.", "timestamp": 1711494045.216486, "uuid": "3301c43a40b841c2a3b82d8101fabd45"}
2024-03-26T23:00:54 {"cpu": 0.13134765625, "cpu_total": 16, "cpu_usage": 0.008209228515625, "memory": 2875.0, "memory_total": 9698.0, "memory_usage": 0.2964528768818313, "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 32 in schedule 4 is alive.", "timestamp": 1711494054.948038, "uuid": "55fdf39c196d49509e305a5ec6bc3f64"}
2024-03-26T23:00:55 {"block_run_id": 96, "block_uuid": "fore_to_postgres", "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Execute PipelineRun 32, BlockRun 96: pipeline fore_to_postgres block fore_to_postgres", "timestamp": 1711494055.199508, "uuid": "4ac049aca7644f879f97a3509e4bfefe"}
2024-03-26T23:00:55 {"block_run_id": 96, "block_uuid": "fore_to_postgres", "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "BlockRun 96 (block_uuid: fore_to_postgres) completes.", "timestamp": 1711494055.644904, "uuid": "cf4f88e984de4e499277a0bba6904517"}
2024-03-26T23:00:56 {"block_run_id": 97, "block_uuid": "test_split_postgres", "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Execute PipelineRun 32, BlockRun 97: pipeline fore_to_postgres block test_split_postgres", "timestamp": 1711494056.215655, "uuid": "23484eb2dd1d4292ac4648c51b5fb25c"}
2024-03-26T23:00:56 {"block_run_id": 97, "block_uuid": "test_split_postgres", "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "EXCEPTION", "message": "BlockRun 97 (block_uuid: test_split_postgres) failed.", "timestamp": 1711494056.544151, "uuid": "0ad73faa0f9d4cdda44cf9fe4860ca11", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 359, in export\n    __process()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 341, in __process\n    self.upload_dataframe(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py\", line 359, in upload_dataframe\n    cursor.copy_expert(f\"\"\"\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"test_scraped_forecasts_final_pkey\"\nDETAIL:  Key (mtn_name, elevation, local_time_issued, local_time_of_forecast)=(nanga_parbat, 8125, 2024-03-26 17:00:00, 2024-03-26 15:00:00) already exists.\nCONTEXT:  COPY test_scraped_forecasts_final, line 1\n\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1580, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["duplicate key value violates unique constraint \"test_scraped_forecasts_final_pkey\"\nDETAIL:  Key (mtn_name, elevation, local_time_issued, local_time_of_forecast)=(nanga_parbat, 8125, 2024-03-26 17:00:00, 2024-03-26 15:00:00) already exists.\nCONTEXT:  COPY test_scraped_forecasts_final, line 1\n"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_postgres
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 359, in export
    __process()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 341, in __process
    self.upload_dataframe(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py", line 359, in upload_dataframe
    cursor.copy_expert(f"""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "test_scraped_forecasts_final_pkey"
DETAIL:  Key (mtn_name, elevation, local_time_issued, local_time_of_forecast)=(nanga_parbat, 8125, 2024-03-26 17:00:00, 2024-03-26 15:00:00) already exists.
CONTEXT:  COPY test_scraped_forecasts_final, line 1

2024-03-26T23:01:04 {"cpu": 0.13037109375, "cpu_total": 16, "cpu_usage": 0.008148193359375, "memory": 2879.0, "memory_total": 9698.0, "memory_usage": 0.29686533305836255, "pipeline_run_id": 32, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "21e5326a3a0e", "level": "INFO", "message": "Pipeline fore_to_postgres for run 32 in schedule 4 is alive.", "timestamp": 1711494064.373855, "uuid": "93b56488f8f6489aa783bc4df019f768"}
