2024-03-26T18:07:34 {"cpu": 0.11572265625, "cpu_total": 16, "cpu_usage": 0.007232666015625, "memory": 1765.0, "memory_total": 9698.0, "memory_usage": 0.18199628789441122, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "0db69d3fbb20", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476454.282565, "uuid": "95a6f6600be745b9bdf6cb98fef6870a"}
2024-03-26T18:07:34 {"cpu": 0.13671875, "cpu_total": 16, "cpu_usage": 0.008544921875, "memory": 1822.0, "memory_total": 9698.0, "memory_usage": 0.18787378840998145, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "0db69d3fbb20", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476454.493408, "uuid": "397c3be6055146cd9c678e5a58ae5327"}
2024-03-26T18:07:34 {"block_run_id": 76, "block_uuid": "scrape_full_fore", "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "0db69d3fbb20", "level": "INFO", "message": "Execute PipelineRun 26, BlockRun 76: pipeline fore_to_postgres block scrape_full_fore", "timestamp": 1711476454.556436, "uuid": "74278c9e791842b9944773da836bd66d"}
2024-03-26T18:07:43 {"cpu": 0.14697265625, "cpu_total": 16, "cpu_usage": 0.009185791015625, "memory": 2017.0, "memory_total": 9698.0, "memory_usage": 0.20798102701587956, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "0db69d3fbb20", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476463.763557, "uuid": "163563e8a53948a99dc32a2498ab6e59"}
2024-03-26T18:07:54 {"cpu": 0.14501953125, "cpu_total": 16, "cpu_usage": 0.009063720703125, "memory": 1852.0, "memory_total": 9698.0, "memory_usage": 0.19096720973396578, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "0db69d3fbb20", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476474.036023, "uuid": "463e6b1d41354a26bf9d39ce000ac799"}
2024-03-26T18:08:12 {"cpu": 0.15771484375, "cpu_total": 16, "cpu_usage": 0.009857177734375, "memory": 1740.0, "memory_total": 9698.0, "memory_usage": 0.17941843679109096, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476492.811334, "uuid": "1cb89d7e2518449c9e83da80c60ac0ee"}
2024-03-26T18:08:13 {"block_run_id": 76, "block_uuid": "scrape_full_fore", "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Execute PipelineRun 26, BlockRun 76: pipeline fore_to_postgres block scrape_full_fore", "timestamp": 1711476493.133485, "uuid": "03e25b6005c14573a3c3172fade96cc6"}
2024-03-26T18:08:22 {"cpu": 0.18359375, "cpu_total": 16, "cpu_usage": 0.011474609375, "memory": 2067.0, "memory_total": 9698.0, "memory_usage": 0.2131367292225201, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476502.223372, "uuid": "16bd4e67d3054fc7970d346f8953c1e7"}
2024-03-26T18:08:32 {"cpu": 0.19775390625, "cpu_total": 16, "cpu_usage": 0.012359619140625, "memory": 2070.0, "memory_total": 9698.0, "memory_usage": 0.21344607135491853, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476512.47732, "uuid": "5846215bd70f4d538baabd79a4d26b56"}
2024-03-26T18:08:42 {"block_run_id": 76, "block_uuid": "scrape_full_fore", "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "BlockRun 76 (block_uuid: scrape_full_fore) completes.", "timestamp": 1711476522.535042, "uuid": "4b66b60e6ff240e687fa0f5524705760"}
2024-03-26T18:08:42 {"cpu": 0.20654296875, "cpu_total": 16, "cpu_usage": 0.012908935546875, "memory": 2046.0, "memory_total": 9698.0, "memory_usage": 0.2109713342957311, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476522.726114, "uuid": "82e8a1688bf84733b146fbb873313ad0"}
2024-03-26T18:08:43 {"block_run_id": 77, "block_uuid": "trivial_transform", "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Execute PipelineRun 26, BlockRun 77: pipeline fore_to_postgres block trivial_transform", "timestamp": 1711476523.164739, "uuid": "d22e28d77b3e46beb821b355258c3ccd"}
2024-03-26T18:08:43 {"block_run_id": 77, "block_uuid": "trivial_transform", "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "BlockRun 77 (block_uuid: trivial_transform) completes.", "timestamp": 1711476523.589109, "uuid": "2b278ef462354150b5f9d847a8e143d2"}
2024-03-26T18:08:53 {"cpu": 0.20947265625, "cpu_total": 16, "cpu_usage": 0.013092041015625, "memory": 2052.0, "memory_total": 9698.0, "memory_usage": 0.21159001856052795, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476533.043749, "uuid": "2f46e3bad5a94080992b753830698ef8"}
2024-03-26T18:08:53 {"block_run_id": 78, "block_uuid": "fore_to_postgres", "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Execute PipelineRun 26, BlockRun 78: pipeline fore_to_postgres block fore_to_postgres", "timestamp": 1711476533.293817, "uuid": "1f12d2948c8c4796b3c9a8d8c0cc8dd4"}
2024-03-26T18:08:58 {"block_run_id": 78, "block_uuid": "fore_to_postgres", "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "EXCEPTION", "message": "BlockRun 78 (block_uuid: fore_to_postgres) failed.", "timestamp": 1711476538.749053, "uuid": "a89bb4983b8d47978bcaf5f01bf7f758", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py\", line 345, in conn\n    return self._ctx\nAttributeError: 'Postgres' object has no attribute '_ctx'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 359, in export\n    __process()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 292, in __process\n    table_exists = self.table_exists(schema_name, table_name)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py\", line 166, in table_exists\n    with self.conn.cursor() as cur:\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py\", line 347, in conn\n    raise ConnectionError(\nConnectionError: No connection currently open. Open a new connection to access this property.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1580, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["No connection currently open. Open a new connection to access this property."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py", line 345, in conn
    return self._ctx
AttributeError: 'Postgres' object has no attribute '_ctx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_postgres
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 359, in export
    __process()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 292, in __process
    table_exists = self.table_exists(schema_name, table_name)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py", line 166, in table_exists
    with self.conn.cursor() as cur:
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py", line 347, in conn
    raise ConnectionError(
ConnectionError: No connection currently open. Open a new connection to access this property.
2024-03-26T18:09:02 {"cpu": 0.21240234375, "cpu_total": 16, "cpu_usage": 0.013275146484375, "memory": 2049.0, "memory_total": 9698.0, "memory_usage": 0.2112806764281295, "pipeline_run_id": 26, "pipeline_schedule_id": 4, "pipeline_uuid": "fore_to_postgres", "hostname": "9c95c407929b", "level": "INFO", "message": "Pipeline fore_to_postgres for run 26 in schedule 4 is alive.", "timestamp": 1711476542.399408, "uuid": "32a27b45bd764cada5fd91896756512c"}
